/*
this data is mainly collected by the open-source project called Cryptii
https://github.com/cryptii/cryptii
*/

const CHARSETS = {
  nato: {
    characters: "abcdefghijklmnopqrstuvwxxyz.",
    words: [
      "Alfa",
      "Bravo",
      "Charlie",
      "Delta",
      "Echo",
      "Foxtrot",
      "Golf",
      "Hotel",
      "India",
      "Juliett",
      "Kilo",
      "Lima",
      "Mike",
      "November",
      "Oscar",
      "Papa",
      "Quebec",
      "Romeo",
      "Sierra",
      "Tango",
      "Uniform",
      "Victor",
      "Whiskey",
      "X-ray",
      "Xray",
      "Yankee",
      "Zulu",
      "Stop",
    ],
    numWords: [
      "Zero",
      "One",
      "Two",
      "Three",
      "Four",
      "Five",
      "Six",
      "Seven",
      "Eight",
      "Nine",
    ],
    spaceWord: "(space)",
  },
  dutch: {
    characters: [
      "a",
      "b",
      "c",
      "d",
      "e",
      "f",
      "g",
      "h",
      "ij",
      "ij",
      "i",
      "j",
      "j",
      "k",
      "l",
      "l",
      "m",
      "n",
      "o",
      "p",
      "q",
      "q",
      "r",
      "r",
      "s",
      "t",
      "u",
      "v",
      "w",
      "x",
      "y",
      "z",
    ],
    words: [
      "Anton",
      "Bernhard",
      "Cornelis",
      "Dirk",
      "Eduard",
      "Ferdinand",
      "Gerard",
      "Hendrik",
      "IJmuiden",
      "IJsbrand",
      "Izaak",
      "Johan",
      "Jacob",
      "Karel",
      "Lodewijk",
      "Leo",
      "Maria",
      "Nico",
      "Otto",
      "Pieter",
      "Quirinius",
      "Quinten",
      "Richard",
      "Rudolf",
      "Simon",
      "Theodoor",
      "Utrecht",
      "Victor",
      "Willem",
      "Xantippe",
      "Ypsilon",
      "Zacharias",
    ],
    numWords: [
      "Nul",
      "Een",
      "Twee",
      "Drie",
      "Vier",
      "Vijf",
      "Zes",
      "Zeven",
      "Acht",
      "Negen",
    ],
    spaceWord: "(spatiebalk)",
  },
  german: {
    characters: "abcdefghijkklmnopqrsstuvwxxyzzäööüüßß",
    words: [
      "Anton",
      "Berta",
      "Cäsar",
      "Dora",
      "Emil",
      "Friedrich",
      "Gustav",
      "Heinrich",
      "Ida",
      "Julius",
      "Kaufmann",
      "Konrad",
      "Ludwig",
      "Martha",
      "Nordpol",
      "Otto",
      "Paula",
      "Quelle",
      "Richard",
      "Samuel",
      "Siegfried",
      "Theodor",
      "Ulrich",
      "Viktor",
      "Wilhelm",
      "Xanthippe",
      "Xaver",
      "Ypsilon",
      "Zacharias",
      "Zürich",
      "Ärger",
      "Ökonom",
      "Österreich",
      "Übermut",
      "Übel",
      "Eszett",
      "Scharfes S",
    ],
    numWords: [
      "Null",
      "Eins",
      "Zwei",
      "Drei",
      "Vier",
      "Fünf",
      "Sechs",
      "Sieben",
      "Acht",
      "Neun",
    ],
    spaceWord: "(Leertaste)",
  },
  swedish: {
    characters: "abcdefghijklmnopqrstuvwxyzåäö",
    words: [
      "Adam",
      "Bertil",
      "Caesar",
      "David",
      "Erik",
      "Filip",
      "Gustav",
      "Helge",
      "Ivar",
      "Johan",
      "Kalle",
      "Ludvig",
      "Martin",
      "Niklas",
      "Olof",
      "Petter",
      "Qvintus",
      "Rudolf",
      "Sigurd",
      "Tore",
      "Urban",
      "Viktor",
      "Wilhelm",
      "Xerxes",
      "Yngve",
      "Zäta",
      "Åke",
      "Ärlig",
      "Östen",
    ],
    numWords: [
      "Nolla",
      "Ett",
      "Tvåa",
      "Trea",
      "Fyra",
      "Femma",
      "Sexa",
      "Sju",
      "Åtta",
      "Nia",
    ],
    spaceWord: "(mellanslag)",
  },
  russian: {
    characters: "абвгдежзийклмнопрстуфхцчшщъыьэюя.",
    words: [
      "Анна",
      "Борис",
      "Василий",
      "Григорий",
      "Дмитрий",
      "Елена",
      "Женя",
      "Зинаида",
      "Иван",
      "Иван краткий",
      "Константин",
      "Леонид",
      "Михаил",
      "Николай",
      "Ольга",
      "Павел",
      "Роман",
      "Семён",
      "Татьяна",
      "Ульяна",
      "Фёдор",
      "Харитон",
      "Цапля",
      "Человек",
      "Шура",
      "Щука",
      "Твёрдый знак",
      "Еры",
      "Мягкий знак",
      "Эхо",
      "Юрий",
      "Яков",
      "Точка",
    ],
    numWords: [
      "Ноль",
      "Один",
      "Два",
      "Три",
      "Четыре",
      "Пять",
      "Шесть",
      "Семь",
      "Восемь",
      "Девять",
    ],
    spaceWord: "(пробел)",
  },
  russian2: {
    characters: "абвгдеёжзийклмнопрстуфхцчшщъыьэюя.",
    words: [
      "Антон",
      "Борис",
      "Василий",
      "Галина",
      "Дмитрий",
      "Елена",
      "Ёлка",
      "Жук",
      "Зоя",
      "Иван",
      "Йот",
      "Киловатт",
      "Леонид",
      "Мария",
      "Николай",
      "Ольга",
      "Павел",
      "Радио",
      "Сергей",
      "Тамара",
      "Ульяна",
      "Фёдор",
      "Харитон",
      "Центр",
      "Человек",
      "Шура",
      "Щука",
      "Твёрдый знак",
      "Игрек",
      "Мягкий знак",
      "Эмма",
      "Юрий",
      "Яков",
      "Точка",
    ],
    numWords: [
      "Ноль",
      "Один",
      "Два",
      "Три",
      "Четыре",
      "Пять",
      "Шесть",
      "Семь",
      "Восемь",
      "Девять",
    ],
    spaceWord: "(пробел)",
  },
};
export default CHARSETS;
