/*the order of elements in each array is crucial to better translation*/

let brailleTable = {
  alphabete: [
    ["“", "⠄⠶"],
    ["“", "⠘⠦"],
    ["”", "⠘⠴"],
    ["‘", "⠄⠦"],
    ["’", "⠄⠴"],
    ['"', "⠠⠶"],
    ["'", "⠄"],
    ["(", "⠐⠣"],
    [")", "⠐⠜"],
    ["{", "⠸⠣"],
    ["}", "⠸⠜"],
    ["&", "⠈⠯"],
    ["<", "⠈⠣"],
    [">", "⠈⠜"],
    ["[", "⠨⠣"],
    ["]", "⠨⠜"],
    ["%", "⠨⠴"],
    ["#", "⠸⠹"],
    ["^", "⠈⠢"],
    ["@", "⠈⠁"],
    ["/", "⠸⠌"],
    ["\\", "⠸⠡"],
    ["$", "⠈⠎"],
    ["£", "⠈⠇"],
    ["€", "⠈⠑"],
    ["¥", "⠈⠽"],
    [" ", "⠀"], //space
    ["-", "⠤"], //hyphen
    ["–", "⠠⠤"], //en dash
    ["—", "⠐⠠⠤"], //em dash
    ["a", "⠁"],
    ["b", "⠃"],
    ["c", "⠉"],
    ["d", "⠙"],
    ["e", "⠑"],
    ["f", "⠋"],
    ["g", "⠛"],
    ["h", "⠓"],
    ["i", "⠊"],
    ["j", "⠚"],
    ["k", "⠅"],
    ["l", "⠇"],
    ["m", "⠍"],
    ["n", "⠝"],
    ["o", "⠕"],
    ["p", "⠏"],
    ["q", "⠟"],
    ["r", "⠗"],
    ["s", "⠎"],
    ["t", "⠞"],
    ["u", "⠥"],
    ["v", "⠧"],
    ["w", "⠺"],
    ["x", "⠭"],
    ["y", "⠽"],
    ["z", "⠵"],
    [",", "⠂"],
    [";", "⠆"],
    [":", "⠒"],
    [".", "⠲"],
    ["?", "⠦"],
    ["!", "⠖"],
    ["‘", "⠄"],
  ],
  numbers: [
    ["=", "⠐⠶"],
    ["+", "⠐⠖"],
    ["*", "⠐⠔"],
    ["1", "⠁"],
    ["2", "⠃"],
    ["3", "⠉"],
    ["4", "⠙"],
    ["5", "⠑"],
    ["6", "⠋"],
    ["7", "⠛"],
    ["8", "⠓"],
    ["9", "⠊"],
    ["0", "⠚"],
  ],
  grade2: [
    ["knowledge", "⠅", /(?<=( [⠠]?|^))knowledge(?=([ ,\.]|$))/g],
    ["enough", "⠢", /(?<=( [⠠]?|^))enough(?=([ ,\.]|$))/g],
    ["people", "⠏", /(?<=( [⠠]?|^))people(?=([ ,\.]|$))/g],
    ["rather", "⠗", /(?<=( [⠠]?|^))rather(?=([ ,\.]|$))/g],
    ["child", "⠡", /(?<=( [⠠]?|^))child(?=([ ,\.]|$))/g],
    ["every", "⠑", /(?<=( [⠠]?|^))every(?=([ ,\.]|$))/g],
    ["quite", "⠟", /(?<=( [⠠]?|^))quite(?=([ ,\.]|$))/g],
    ["shall", "⠩", /(?<=( [⠠]?|^))shall(?=([ ,\.]|$))/g],
    ["still", "⠌", /(?<=( [⠠]?|^))still(?=([ ,\.]|$))/g],
    ["which", "⠱", /(?<=( [⠠]?|^))which(?=([ ,\.]|$))/g],
    ["from", "⠋", /(?<=( [⠠]?|^))from(?=([ ,\.]|$))/g],
    ["have", "⠓", /(?<=( [⠠]?|^))have(?=([ ,\.]|$))/g],
    ["just", "⠚", /(?<=( [⠠]?|^))just(?=([ ,\.]|$))/g],
    ["like", "⠇", /(?<=( [⠠]?|^))like(?=([ ,\.]|$))/g],
    ["more", "⠍", /(?<=( [⠠]?|^))more(?=([ ,\.]|$))/g],
    ["that", "⠞", /(?<=( [⠠]?|^))that(?=([ ,\.]|$))/g],
    ["this", "⠹", /(?<=( [⠠]?|^))this(?=([ ,\.]|$))/g],
    ["very", "⠧", /(?<=( [⠠]?|^))very(?=([ ,\.]|$))/g],
    ["were", "⠶", /(?<=( [⠠]?|^))were(?=([ ,\.]|$))/g],
    ["will", "⠺", /(?<=( [⠠]?|^))will(?=([ ,\.]|$))/g],
    ["but", "⠃", /(?<=( [⠠]?|^))but(?=([ ,\.]|$))/g],
    ["can", "⠉", /(?<=( [⠠]?|^))can(?=([ ,\.]|$))/g],
    ["his", "⠦", /(?<=( [⠠]?|^))his(?=([ ,\.]|$))/g],
    ["its", "⠭⠎", /(?<=( [⠠]?|^))its(?=([ ,\.]|$))/g],
    ["not", "⠝", /(?<=( [⠠]?|^))not(?=([ ,\.]|$))/g],
    ["out", "⠳", /(?<=( [⠠]?|^))out(?=([ ,\.]|$))/g],
    ["was", "⠴", /(?<=( [⠠]?|^))was(?=([ ,\.]|$))/g],
    ["you", "⠽", /(?<=( [⠠]?|^))you(?=([ ,\.]|$))/g],
    ["as", "⠵", /(?<=( [⠠]?|^))as(?=([ ,\.]|$))/g],
    ["be", "⠆", /(?<=( [⠠]?|^))be(?=([ ,\.]|$))/g],
    ["do", "⠙", /(?<=( [⠠]?|^))do(?=([ ,\.]|$))/g],
    ["go", "⠛", /(?<=( [⠠]?|^))go(?=([ ,\.]|$))/g],
    ["it", "⠭", /(?<=( [⠠]?|^))it(?=([ ,\.]|$))/g],
    ["so", "⠎", /(?<=( [⠠]?|^))so(?=([ ,\.]|$))/g],
    ["us", "⠥", /(?<=( [⠠]?|^))us(?=([ ,\.]|$))/g],

    ["yourselves", "⠽⠗⠧⠎", /yourselves/g],
    ["themselves", "⠮⠍⠧⠎", /themselves/g],
    ["perceiving", "⠏⠻⠉⠧⠛", /perceiving/g],
    ["conceiving", "⠒⠉⠧⠛", /conceiving/g],
    ["altogether", "⠁⠇⠞", /altogether/g],
    ["rejoicing", "⠗⠚⠉⠛", /rejoicing/g],
    ["receiving", "⠗⠉⠧⠛", /receiving/g],
    ["ourselves", "⠳⠗⠧⠎", /ourselves/g],
    ["necessary", "⠝⠑⠉", /necessary/g],
    ["immediate", "⠊⠍⠍", /immediate/g],
    ["declaring", "⠙⠉⠇⠛", /declaring/g],
    ["deceiving", "⠙⠉⠧⠛", /deceiving/g],
    ["character", "⠐⠡", /character/g],
    ["afterward", "⠁⠋⠺", /afterward/g],
    ["afternoon", "⠁⠋⠝", /afternoon/g],
    ["according", "⠁⠉", /according/g],
    ["yourself", "⠽⠗⠋", /yourself/g],
    ["tomorrow", "⠞⠍", /tomorrow/g],
    ["together", "⠞⠛⠗", /together/g],
    ["question", "⠐⠟", /question/g],
    ["perceive", "⠏⠻⠉⠧", /perceive/g],
    ["conceive", "⠒⠉⠧", /conceive/g],
    ["children", "⠡⠝", /children/g],
    ["although", "⠁⠇⠹", /although/g],
    ["tonight", "⠞⠝", /tonight/g],
    ["thyself", "⠹⠽⠋", /thyself/g],
    ["through", "⠐⠹", /through/g],
    ["rejoice", "⠗⠚⠉", /rejoice/g],
    ["receive", "⠗⠉⠧", /receive/g],
    ["perhaps", "⠏⠻⠓", /perhaps/g],
    ["oneself", "⠐⠕⠋", /oneself/g],
    ["neither", "⠝⠑⠊", /neither/g],
    ["himself", "⠓⠍⠋", /himself/g],
    ["herself", "⠓⠻⠋", /herself/g],
    ["declare", "⠙⠉⠇", /declare/g],
    ["deceive", "⠙⠉⠧", /deceive/g],
    ["braille", "⠃⠗⠇", /braille/g],
    ["between", "⠆⠞", /between/g],
    ["beneath", "⠆⠝", /beneath/g],
    ["because", "⠆⠉", /because/g],
    ["already", "⠁⠇⠗", /already/g],
    ["against", "⠁⠛⠌", /against/g],
    ["friend", "⠋⠗", /friend/g],
    ["spirit", "⠸⠎", /spirit/g],
    ["should", "⠩⠙", /should/g],
    ["myself", "⠍⠽⠋", /myself/g],
    ["mother", "⠐⠍", /mother/g],
    ["little", "⠇⠇", /little/g],
    ["letter", "⠇⠗", /letter/g],
    ["itself", "⠭⠋", /itself/g],
    ["either", "⠑⠊", /either/g],
    ["father", "⠐⠋", /father/g],
    ["cannot", "⠸⠉", /cannot/g],
    ["beyond", "⠆⠽", /beyond/g],
    ["beside", "⠆⠎", /beside/g],
    ["behind", "⠆⠓", /behind/g],
    ["before", "⠆⠋", /before/g],
    ["always", "⠁⠇⠺", /always/g],
    ["almost", "⠁⠇⠍", /almost/g],
    ["across", "⠁⠉⠗", /across/g],
    ["first", "⠋⠌", /first/g],
    ["whose", "⠘⠱", /whose/g],
    ["young", "⠐⠽", /young/g],
    ["would", "⠺⠙", /would/g],
    ["world", "⠸⠺", /world/g],
    ["where", "⠐⠱", /where/g],
    ["under", "⠐⠥", /under/g],
    ["today", "⠞⠙", /today/g],
    ["those", "⠘⠹", /those/g],
    ["these", "⠘⠮", /these/g],
    ["there", "⠐⠮", /there/g],
    ["their", "⠸⠮", /their/g],
    ["right", "⠐⠗", /right/g],
    ["quick", "⠟⠅", /quick/g],
    ["ought", "⠐⠳", /ought/g],
    ["great", "⠛⠗⠞", /great/g],
    ["could", "⠉⠙", /could/g],
    ["blind", "⠃⠇", /blind/g],
    ["below", "⠆⠇", /below/g],
    ["again", "⠁⠛", /again/g],
    ["after", "⠁⠋", /after/g],
    ["above", "⠁⠃⠧", /above/g],
    ["about", "⠁⠃", /about/g],
    ["ever", "⠐⠑", /ever/g],
    ["your", "⠽⠗", /your/g],
    ["work", "⠐⠺", /work/g],
    ["word", "⠘⠺", /word/g],
    ["with", "⠾", /with/g],
    ["upon", "⠘⠥", /upon/g],
    ["time", "⠐⠞", /time/g],
    ["such", "⠎⠡", /such/g],
    ["some", "⠐⠎", /some/g],
    ["said", "⠎⠙", /said/g],
    ["part", "⠐⠏", /part/g],
    ["paid", "⠏⠙", /paid/g],
    ["name", "⠐⠝", /name/g],
    ["must", "⠍⠌", /must/g],
    ["much", "⠍⠡", /much/g],
    ["many", "⠸⠍", /many/g],
    ["lord", "⠐⠇", /lord/g],
    ["know", "⠐⠅", /know/g],
    ["here", "⠐⠓", /here/g],
    ["good", "⠛⠙", /good/g],
    ["also", "⠁⠇", /also/g],

    ["ance", "⠨⠑", /(?<=[^ ]+)ance(?=([ ,\.]|$))/g],
    ["ment", "⠰⠞", /(?<=[^ ]+)ment(?=([ ,\.]|$))/g],
    ["ness", "⠰⠎", /(?<=[^ ]+)ness(?=([ ,\.]|$))/g],
    ["ound", "⠨⠙", /(?<=[^ ]+)ound(?=([ ,\.]|$))/g],
    ["ount", "⠨⠞", /(?<=[^ ]+)ount(?=([ ,\.]|$))/g],
    ["sion", "⠨⠝", /(?<=[^ ]+)sion(?=([ ,\.]|$))/g],
    ["tion", "⠰⠝", /(?<=[^ ]+)tion(?=([ ,\.]|$))/g],
    ["ence", "⠰⠑", /(?<=[^ ]+)ence(?=([ ,\.]|$))/g],
    ["less", "⠨⠎", /(?<=[^ ]+)less(?=([ ,\.]|$))/g],
    ["ff", "⠖", /(?<=[^ ]+)ff(?=[^ ]+)/g],
    ["ful", "⠰⠇", /(?<=[^ ]+)ful(?=([ ,\.]|$))/g],
    ["gg", "⠶", /(?<=[^ ]+)gg(?=[^ ]+)/g],
    ["ity", "⠰⠽", /(?<=[^ ]+)ity(?=([ ,\.]|$))/g],
    ["ong", "⠰⠛", /(?<=[^ ]+)ong(?=([ ,\.]|$))/g],
    ["bb", "⠆", /(?<=[^ ]+)bb(?=[^ ]+)/g],
    ["cc", "⠒", /(?<!(⠼[^ ]+)|⠼)(?<=[^ ]+)cc(?=[^ ]+)/g],
    ["con", "⠒", /(?<=( |^))con(?=[^ ]+)/g],
    ["dis", "⠲", /(?<=( |^))dis(?=[^ ⠲]+)/g],
    ["ea", "⠂", /(?<!(⠼[^ ]+)|⠼)(?<=([^ ]+))ea(?=[^ ]+)/g],
    ["be", "⠆", /(?<=( |^))be(?=[^ ]+)/g],
    ["for", "⠿", /for/g],
    ["the", "⠮", /the/g],
    ["one", "⠐⠕", /one/g],
    ["ing", "⠬", /ing/g],
    ["him", "⠓⠍", /him/g],
    ["had", "⠸⠓", /had/g],
    ["day", "⠐⠙", /day/g],
    ["and", "⠯", /and/g],
    ["ch", "⠡", /ch/g],
    ["gh", "⠣", /(?<![⠐⠸⠈⠨])gh/g],
    ["er", "⠻", /er/g],
    ["en", "⠢", /en/g],
    ["wh", "⠱", /wh/g],
    ["th", "⠹", /th/g],
    ["st", "⠌", /st/g],
    ["sh", "⠩", /sh/g],
    ["ow", "⠪", /ow/g],
    ["ou", "⠳", /ou/g],
    ["of", "⠷", /of/g],
    ["ed", "⠫", /ed/g],
    ["in", "⠔", /in/g],
    ["ar", "⠜", /(?<![⠐⠸⠈⠨])ar/g],
  ],
  punctuation: [
    ["⠼", /\d+[.,]?\d*/g, /⠼(?=\d+)/g],
    ["⠠", /(?<=([^A-Z]|^))[A-Z](?=([^A-Z]|$))/g, /(?<!⠠)⠠(?![⠤⠠])/g],
    ["⠠⠠", /[A-Z]{2,}/g, /(⠠{2})/g],
    ["⠰", /(?<=\d)[a-j]+/g, /(?<=\d)⠰/g],
    //["⠦", /(?<!(["].+))"(?=(.+"))(?!("))/g, /bb/g, "⠠⠶"],
    //["⠴", /(?<=(⠦.+))(?<!("))"/g, /gg/g, "⠠⠶"],
  ],
  allowedCombs: {
    again: ["again", "against", "agains"],
    upon: ["upon", "hereupon", "thereupon", "whereupon"],
    these: ["these"],
    those: ["those"],
    whose: ["whose", "whosesoever", "whosever"],
    there: [
      "there",
      "thereabout",
      "thereabouts",
      "thereafter",
      "thereat",
      "thereby",
      "therefor",
      "therefore",
      "therefrom",
      "therein",
      "thereinto",
      "thereof",
      "thereon",
      "thereunder",
      "thereunto",
      "thereupon",
      "thereto",
      "theretofore",
      "therewith",
      "therewithal",
    ],
    about: [
      "about",
      "aboutface",
      "aboutfaced",
      "aboutfacer",
      "aboutfacing",
      "aboutturn",
      "aboutturned",
      "eastabout",
      "gadabout",
      "hereabout",
      "knockabout",
      "layabout",
      "northabout",
      "rightabout",
      "roundabout",
      "roustabout",
      "runabout",
      "southabout",
      "stirabout",
      "thereabout",
      "turnabout",
      "walkabout",
      "westabout",
      "whereabout",
    ],
    above: [
      "above",
      "aboveboard",
      "aboveground",
      "abovementioned",
      "hereinabove",
    ],
    according: ["according", "accordingly", "unaccording", "unaccordingly"],
    across: ["across", "readacross"],
    after: [
      "after",
      "afterbattle",
      "afterbirth",
      "afterbreakfast",
      "afterburn",
      "afterburned",
      "afterburner",
      "afterburning",
      "aftercare",
      "afterclap",
      "aftercoffee",
      "afterdamp",
      "afterdark",
      "afterdeck",
      "afterdinner",
      "afterflow",
      "aftergame",
      "afterglow",
      "afterguard",
      "afterhatch",
      "afterhatches",
      "afterhour",
      "afterlife",
      "afterlight",
      "afterlives",
      "afterlunch",
      "afterlunches",
      "aftermarket",
      "aftermatch",
      "aftermatches",
      "aftermath",
      "aftermeeting",
      "aftermidday",
      "aftermidnight",
      "aftermost",
      "afterpain",
      "afterparties",
      "afterparty",
      "afterpiece",
      "afterplay",
      "aftersale",
      "afterschool",
      "aftersensation",
      "aftershave",
      "aftershock",
      "aftershow",
      "aftershower",
      "aftersupper",
      "aftertaste",
      "aftertax",
      "aftertaxes",
      "aftertea",
      "aftertheatre",
      "afterthought",
      "aftertime",
      "aftertreatment",
      "afterword",
      "afterwork",
      "afterworld",
      "hereafter",
      "hereinafter",
      "morningafter",
      "thereafter",
      "thereinafter",
      "whereafter",
      "whereinafter",
    ],
    afternoon: ["afternoon", "afternoontea", "goodafternoon", "midafternoon"],
    again: [
      "again",
      "hereagain",
      "hereinagain",
      "thereagain",
      "thereinagain",
      "whereagain",
      "whereinagain",
    ],
    against: ["against", "hereagainst", "thereagainst", "whereagainst"],
    also: ["also"],
    altogether: ["altogether"],
    below: ["below", "belowdeck", "belowground", "belowmentioned"],
    beneath: ["beneath", "beneathdeck", "beneathground"],
    between: ["between", "betweendeck", "betweentime", "betweenwhile"],
    blind: [
      "blind",
      "blindfish",
      "blindfishes",
      "blindfold",
      "blindfolded",
      "blindfolder",
      "blindfolding",
      "blindly",
      "blindman",
      "blindmen",
      "blindness",
      "blindnesses",
      "blindside",
      "blindsided",
      "blindsider",
      "blindsiding",
      "blindsight",
      "blindstories",
      "blindstory",
      "blindworm",
      "colorblind",
      "colorblindness",
      "colorblindnesses",
      "colourblind",
      "colourblindness",
      "colourblindnesses",
      "deafblind",
      "deafblindness",
      "deafblindnesses",
      "purblind",
      "purblindly",
      "purblindness",
      "purblindnesses",
      "snowblind",
      "snowblindness",
      "snowblindnesses",
      "unblindfold",
      "unblindfolded",
      "unblindfolding",
    ],
    braille: [
      "braille",
      "brailled",
      "brailler",
      "braillewriter",
      "braillewriting",
      "brailley",
      "misbraille",
      "misbrailled",
      "rebraille",
      "rebrailled",
      "rebrailler",
      "unbraille",
      "unbrailled",
    ],
    could: [
      "could",
      "could've",
      "coulda",
      "couldest",
      "couldn't",
      "couldn't've",
      "couldst",
    ],
    deceive: [
      "deceive",
      "deceived",
      "deceiver",
      "archdeceiver",
      "undeceive",
      "undeceived",
      "undeceiver",
    ],
    deceiving: ["deceiving", "undeceiving"],
    declare: ["declare", "declared", "declarer", "undeclare", "undeclared"],
    first: [
      "first",
      "firstaid",
      "firstaider",
      "firstborn",
      "firstclass",
      "firstclasses",
      "firstday",
      "firstdayer",
      "firstfruit",
      "firstfruiting",
      "firstgeneration",
      "firsthand",
      "firsthanded",
      "firstling",
      "firstly",
      "firstness",
      "firstnight",
      "firstnighter",
      "firstrate",
      "firstrated",
      "firstrating",
      "firststring",
      "feetfirst",
      "headfirst",
      "tailfirst",
    ],
    friend: [
      "friend",
      "friendless",
      "friendlessness",
      "friendlessnesses",
      "friendlier",
      "friendlies",
      "friendliest",
      "friendliness",
      "friendlinesses",
      "friendly",
      "friendship",
      "befriend",
      "boyfriend",
      "defriend",
      "galfriend",
      "gentlemanfriend",
      "gentlemenfriends",
      "girlfriend",
      "guyfriend",
      "ladyfriend",
      "manfriend",
      "menfriends",
      "penfriend",
      "schoolfriend",
      "unfriend",
      "unfriendlier",
      "unfriendliest",
      "unfriendliness",
      "unfriendlinesses",
      "unfriendly",
      "womanfriend",
      "womenfriends",
    ],
    good: [
      "good",
      "goodafternoon",
      "goodby",
      "goodbye",
      "goodbyeing",
      "goodbying",
      "goodday",
      "gooder",
      "goodest",
      "goodevening",
      "goodfellow",
      "goodfellowship",
      "goodhearted",
      "goodheartedly",
      "goodheartedness",
      "goodhumor",
      "goodhumored",
      "goodhumoredly",
      "goodhumoredness",
      "goodhumorednesses",
      "goodhumour",
      "goodhumoured",
      "goodhumouredly",
      "goodhumouredness",
      "goodhumourednesses",
      "goodie",
      "goodish",
      "goodlier",
      "goodliest",
      "goodliness",
      "goodlook",
      "goodlooker",
      "goodlooking",
      "goodly",
      "goodman",
      "goodmen",
      "goodmorning",
      "goodnature",
      "goodnatured",
      "goodnaturedly",
      "goodnaturedness",
      "goodness",
      "goodnesses",
      "goodnight",
      "goodsize",
      "goodsized",
      "goodtempered",
      "goodtemperedly",
      "goodtime",
      "goodun",
      "goodwife",
      "goodwill",
      "goodwilled",
      "goodwives",
      "goody",
      "goodyear",
      "feelgood",
      "scattergood",
      "supergood",
    ],
    great: [
      "great",
      "greatcoat",
      "greaten",
      "greatened",
      "greatener",
      "greatening",
      "greater",
      "greatest",
      "greatgrandaunt",
      "greatgrandchild",
      "greatgrandchildren",
      "greatgranddad",
      "greatgranddaughter",
      "greatgrandfather",
      "greatgrandfatherhood",
      "greatgrandma",
      "greatgrandmother",
      "greatgrandmotherhood",
      "greatgrandnephew",
      "greatgrandniece",
      "greatgrandpa",
      "greatgrandparent",
      "greatgrandparenthood",
      "greatgrandson",
      "greatgranduncle",
      "greathearted",
      "greatheartedly",
      "greatheartedness",
      "greatheartednesses",
      "greatly",
      "greatnephew",
      "greatness",
      "greatnesses",
      "greatniece",
      "greatsword",
      "greatuncle",
    ],
    him: ["him", "himbo", "himboes"],
    immediate: ["immediate", "immediately", "immediateness"],
    letter: [
      "letter",
      "letterbomb",
      "letterbombed",
      "letterbomber",
      "letterbombing",
      "letterbox",
      "letterboxed",
      "letterboxer",
      "letterboxes",
      "letterboxing",
      "letterbodies",
      "letterbody",
      "lettered",
      "letterer",
      "letterform",
      "letterhead",
      "letterheading",
      "lettering",
      "letterman",
      "lettermen",
      "letteropener",
      "letterperfect",
      "letterpress",
      "letterpressed",
      "letterpresses",
      "letterpressing",
      "letterquality",
      "letterspace",
      "letterspaced",
      "letterspacing",
      "lettertext",
      "bloodletter",
      "chainletter",
      "hateletter",
      "loveletter",
      "newsletter",
      "reletter",
      "relettered",
      "relettering",
      "unlettered",
    ],
    little: [
      "little",
      "littled",
      "littleneck",
      "littleness",
      "littlenesses",
      "littler",
      "littlest",
      "belittle",
      "belittled",
      "belittlement",
      "belittler",
    ],
    much: [
      "much",
      "muchly",
      "muchness",
      "forasmuch",
      "inasmuch",
      "insomuch",
      "overmuch",
    ],
    must: [
      "must",
      "must've",
      "musta",
      "mustard",
      "mustier",
      "mustiest",
      "mustily",
      "mustiness",
      "mustn't",
      "mustn't've",
      "musty",
    ],
    necessary: ["necessary", "unnecessary"],
    paid: [
      "paid",
      "highest-paid",
      "highlypaid",
      "illpaid",
      "lowlypaid",
      "overpaid",
      "poorlypaid",
      "postpaid",
      "prepaid",
      "repaid",
      "underpaid",
      "unpaid",
      "wellpaid",
    ],
    perceive: [
      "perceive",
      "perceived",
      "perceiver",
      "apperceive",
      "apperceived",
      "apperceiver",
      "misperceive",
      "misperceived",
      "misperceiver",
      "unperceive",
      "unperceived",
    ],
    perceiving: ["perceiving", "apperceiving", "misperceiving", "unperceiving"],
    perhaps: ["perhaps", "perhapses"],
    quick: [
      "quick",
      "quickdraw",
      "quicken",
      "quickened",
      "quickener",
      "quickening",
      "quicker",
      "quickest",
      "quickfire",
      "quickfiring",
      "quickfreeze",
      "quickfreezing",
      "quickfroze",
      "quickfrozen",
      "quickie",
      "quickish",
      "quickishly",
      "quicklime",
      "quickly",
      "quickness",
      "quicknesses",
      "quicksand",
      "quickset",
      "quicksilver",
      "quicksilvered",
      "quicksilvering",
      "quicksnap",
      "quickstep",
      "quickstepped",
      "quickstepper",
      "quickstepping",
      "quicktempered",
      "quicktime",
      "quickwitted",
      "quickwittedly",
      "quickwittedness",
      "quicky",
      "doublequick",
      "superquick",
      "unquick",
    ],
    receive: [
      "receive",
      "received",
      "receiver",
      "receivership",
      "preceive",
      "preceiver",
      "unreceived",
    ],
    receiving: ["receiving", "preceiving"],
    rejoice: [
      "rejoice",
      "rejoiced",
      "rejoiceful",
      "rejoicefully",
      "rejoicefulness",
      "rejoicer",
      "unrejoice",
      "unrejoiced",
      "unrejoicer",
      "unrejoiceful",
      "unrejoicefully",
      "unrejoicefulness",
    ],
    rejoicing: ["rejoicing", "rejoicingly", "unrejoicing", "unrejoicingly"],
    said: [
      "said",
      "saidest",
      "saidst",
      "aforesaid",
      "foresaid",
      "gainsaid",
      "missaid",
    ],
    should: [
      "should",
      "should've",
      "shoulda",
      "shouldest",
      "shouldn't",
      "shouldn't've",
      "shouldst",
    ],
    such: ["suchas", "such", "suchlike", "nonesuch", "nonsuch", "somesuch"],
    yourself: ["yourself", "do-it-yourselfer"],
    would: [
      "would",
      "would've",
      "woulda",
      "wouldest",
      "wouldn't",
      "wouldn't've",
      "wouldst",
      "'twould",
      "'twould've",
      "'twoulda",
      "'twouldn't",
      "'twouldn't've",
    ],
    //ou: ["our"],
    //yourselves: [],
    //themselves: [],
    //conceiving: [],
    //ourselves: [],
    //declaring: [],
    character: [
      "character",
      "characters",
      "characteristic",
      "characteristics",
      "incharacter",
      "characteristicly",
    ],
    afterward: ["afterward", "afterwards"],
    tomorrow: ["tomorrow"],
    //together: [],
    //question: [],
    //conceive: [],
    children: ["children"],
    //although: [],
    //tonight: [],
    //thyself: [],
    //through: [],
    //oneself: [],
    neither: ["neither"],
    //himself: [],
    //herself: [],
    because: ["because", "allbecause", "allbecauseof", "becauseof"],
    //already: [],
    //spirit: [],
    //myself: [],
    //mother: [],
    //itself: [],
    either: ["either"],
    //father: [],
    //cannot: [],
    //beyond: [],
    //beside: [],
    //behind: [],
    //before: [],
    //always: [],
    //almost: [],
    //young: [],
    //world: [],
    //where: [],
    //under: [],
    //today: [],
    //their: [],
    //right: [],
    //ought: [],
    //ever: [],
    your: ["your"],
    //work: [],
    //word: ["word", "words", "wordle"],
    with: ["with", "withdraw", "withstand"],
    //time: ["time", "timeless", "ontime", "intime", "timeful"],
    //some: ["some", "someone", "somepeople"],
    //part: ["partake", "part", "parts", "parttime"],
    //name: ["name", "names", "myname", "yourname", "firstname", "lastname"],
    //many: ["many", "somany"],
    //lord: ["lord", "landlord", "lords"],
    know: [
      "knowledge",
      "know",
      "known",
      "knowledgable",
      "acknowledge",
      "acknowledged",
    ],
    //here: ["here", "hereafter", "adhere"],
  },
};

export default brailleTable;
