/*the order of elements in each array is crucial to better translation*/

let brailleTable = {
  alphabete: [
    ["—", "⠐⠠⠤"], //em dash
    ["–", "⠠⠤"], //en dash
    ["=", "⠐⠶"],
    ["+", "⠐⠖"],
    ["*", "⠐⠔"],
    ["“", "⠄⠶"],
    ["“", "⠘⠦"],
    ["”", "⠘⠴"],
    ["‘", "⠄⠦"],
    ["’", "⠄⠴"],
    ['"', "⠠⠶"],
    ["'", "⠄"],
    ["(", "⠐⠣"],
    [")", "⠐⠜"],
    ["{", "⠸⠣"],
    ["}", "⠸⠜"],
    ["&", "⠈⠯"],
    ["<", "⠈⠣"],
    [">", "⠈⠜"],
    ["[", "⠨⠣"],
    ["]", "⠨⠜"],
    ["%", "⠨⠴"],
    ["#", "⠸⠹"],
    ["^", "⠈⠢"],
    ["@", "⠈⠁"],
    ["/", "⠸⠌"],
    ["\\", "⠸⠡"],
    ["$", "⠈⠎"],
    ["£", "⠈⠇"],
    ["€", "⠈⠑"],
    ["¥", "⠈⠽"],
    [" ", "⠀"], //space
    ["-", "⠤"], //hyphen

    ["a", "⠁"],
    ["b", "⠃"],
    ["c", "⠉"],
    ["d", "⠙"],
    ["e", "⠑"],
    ["f", "⠋"],
    ["g", "⠛"],
    ["h", "⠓"],
    ["i", "⠊"],
    ["j", "⠚"],
    ["k", "⠅"],
    ["l", "⠇"],
    ["m", "⠍"],
    ["n", "⠝"],
    ["o", "⠕"],
    ["p", "⠏"],
    ["q", "⠟"],
    ["r", "⠗"],
    ["s", "⠎"],
    ["t", "⠞"],
    ["u", "⠥"],
    ["v", "⠧"],
    ["w", "⠺"],
    ["x", "⠭"],
    ["y", "⠽"],
    ["z", "⠵"],
    [",", "⠂"],
    [";", "⠆"],
    [":", "⠒"],
    [".", "⠲"],
    ["?", "⠦"],
    ["!", "⠖"],
    ["‘", "⠄"],
  ],
  numbers: [
    ["0", "⠚"],
    ["1", "⠁"],
    ["2", "⠃"],
    ["3", "⠉"],
    ["4", "⠙"],
    ["5", "⠑"],
    ["6", "⠋"],
    ["7", "⠛"],
    ["8", "⠓"],
    ["9", "⠊"],
  ],
  grade2: [
    ["knowledge", "⠅", /(?<=(( |^)⠠{0,2}))knowledge(?=([ ,.]|$))/g],
    ["enough", "⠢", /(?<=(( |^)⠠{0,2}))enough(?=([ ,.]|$))/g],
    ["people", "⠏", /(?<=(( |^)⠠{0,2}))people(?=([ ,.]|$))/g],
    ["rather", "⠗", /(?<=(( |^)⠠{0,2}))rather(?=([ ,.]|$))/g],
    ["child", "⠡", /(?<=(( |^)⠠{0,2}))child(?=([ ,.]|$))/g],
    ["every", "⠑", /(?<=(( |^)⠠{0,2}))every(?=([ ,.]|$))/g],
    ["quite", "⠟", /(?<=(( |^)⠠{0,2}))quite(?=([ ,.]|$))/g],
    ["shall", "⠩", /(?<=(( |^)⠠{0,2}))shall(?=([ ,.]|$))/g],
    ["still", "⠌", /(?<=(( |^)⠠{0,2}))still(?=([ ,]|$))/g],
    ["which", "⠱", /(?<=(( |^)⠠{0,2}))which(?=([ ,.]|$))/g],
    ["from", "⠋", /(?<=(( |^)⠠{0,2}))from(?=([ ,.]|$))/g],
    ["have", "⠓", /(?<=(( |^)⠠{0,2}))have(?=([ ,.]|$))/g],
    ["just", "⠚", /(?<=(( |^)⠠{0,2}))just(?=([ ,.]|$))/g],
    ["like", "⠇", /(?<=(( |^)⠠{0,2}))like(?=([ ,.]|$))/g],
    ["more", "⠍", /(?<=(( |^)⠠{0,2}))more(?=([ ,.]|$))/g],
    ["that", "⠞", /(?<=(( |^)⠠{0,2}))that(?=([ ,.]|$))/g],
    ["this", "⠹", /(?<=(( |^)⠠{0,2}))this(?=([ ,.]|$))/g],
    ["very", "⠧", /(?<=(( |^)⠠{0,2}))very(?=([ ,.]|$))/g],
    ["were", "⠶", /(?<=(( |^)⠠{0,2}))were(?=([ ,.]|$))/g],
    ["will", "⠺", /(?<=(( |^)⠠{0,2}))will(?=([ ,.]|$))/g],
    ["but", "⠃", /(?<=(( |^)⠠{0,2}))but(?=([ ,.]|$))/g],
    ["can", "⠉", /(?<=(( |^)⠠{0,2}))can(?=([ ,.]|$))/g],
    ["his", "⠦", /(?<=(( |^)⠠{0,2}))his(?=([ ,.]|$))/g],
    ["its", "⠭⠎", /(?<=(( |^)⠠{0,2}))its(?=([ ,.]|$))/g],
    ["not", "⠝", /(?<=(( |^)⠠{0,2}))not(?=([ ,.]|$))/g],
    ["out", "⠳", /(?<=(( |^)⠠{0,2}))out(?=([ ,.]|$))/g],
    ["was", "⠴", /(?<=(( |^)⠠{0,2}))was(?=([ ,.]|$))/g],
    ["you", "⠽", /(?<=(( |^)⠠{0,2}))you(?=([ ,.] |$))/g],
    ["as", "⠵", /(?<=(( |^)⠠{0,2}))as(?=([ ,.]|$))/g],
    ["be", "⠆", /(?<=(( |^)⠠{0,2}))be(?=([ ,.]|$))/g],
    ["do", "⠙", /(?<=(( |^)⠠{0,2}))do(?=([ ,.]|$))/g],
    ["go", "⠛", /(?<=(( |^)⠠{0,2}))go(?=([ ,.]|$))/g],
    ["it", "⠭", /(?<=(( |^)⠠{0,2}))it(?=([ ,.]|$))/g],
    ["so", "⠎", /(?<=(( |^)⠠{0,2}))so(?=([ ,.]|$))/g],
    ["us", "⠥", /(?<=(( |^)⠠{0,2}))us(?=([ ,.]|$))/g],

    ["yourselves", "⠽⠗⠧⠎", /(?<=(^|[ ,.]))yourselves(?=([ ,.]|$))/g],
    ["themselves", "⠮⠍⠧⠎", /themselves/g],
    ["perceiving", "⠏⠻⠉⠧⠛", /perceiving/g],
    ["conceiving", "⠒⠉⠧⠛", /(?<=(^|[ ,.]))conceiving(?=([ ,.]|$))/g],
    ["altogether", "⠁⠇⠞", /(?<=(^|[ ,.]))altogether(?=([ ,.]|$))/g],
    [
      "rejoicing",
      "⠗⠚⠉⠛",
      /(?<=((^|[ ,.])(un)?))rejoicing(?=((ly)?([ ,.]|$)))/g,
    ],
    ["receiving", "⠗⠉⠧⠛", /(?<=((^|[ ,.])(p)?))receiving(?=([ ,.]|$))/g],
    ["ourselves", "⠳⠗⠧⠎", /ourselves/g],
    ["necessary", "⠝⠑⠉", /(?<=((^|[ ,.])(un)?))necessary(?=([ ,.]|$))/g],
    ["immediate", "⠊⠍⠍", /(?<=(^|[ ,.]))immediate(?=((ly|ness)?([ ,.]|$)))/g],
    [
      "declaring",
      "⠙⠉⠇⠛",
      /(?<=((^|[ ,.])(un)?))declaring(?=((ly|ness)?([ ,.]|$)))/g,
    ],
    [
      "deceiving",
      "⠙⠉⠧⠛",
      /(?<=((^|[ ,.])(un)?))deceiving(?=((ly)?([ ,.]|$)))/g,
    ],
    ["character", "⠐⠡", /character/g],
    ["afterward", "⠁⠋⠺", /(?<=((^|[ ,.])(in)?))afterward(?=((s)?([ ,.]|$)))/g],
    [
      "afternoon",
      "⠁⠋⠝",
      /(?<=((^|[ ,.])(good|mid)?))afternoon(?=((tea)?([ ,.]|$)))/g,
    ],
    ["according", "⠁⠉", /(?<=((^|[ ,.])(un)?))according(?=((ly)?([ ,.]|$)))/g],
    ["yourself", "⠽⠗⠋", /(?<=(^|[ ,.]))yourself(?=([ ,.]|$))/g],
    ["tomorrow", "⠞⠍", /(?<=(^|[ ,.]))tomorrow(?=([ ,.]|$))/g],
    ["together", "⠞⠛⠗", /(?<=(^|[ ,.]))together(?=([ ,.]|$))/g],
    ["question", "⠐⠟", /question/g],
    ["perceive", "⠏⠻⠉⠧", /perceive/g],
    ["conceive", "⠒⠉⠧", /(?<=((^|[ ,.])(un)?))conceive(?=((d|r)?([ ,.]|$)))/g],
    ["children", "⠡⠝", /(?<=(^|[ ,.]))children(?=([ ,.']|$))/g],
    ["although", "⠁⠇⠹", /although/g],
    ["tonight", "⠞⠝", /(?<=(^|[ ,.]))tonight(?=([ ,.]|$))/g],
    ["thyself", "⠹⠽⠋", /thyself/g],
    ["through", "⠐⠹", /through/g],
    [
      "rejoice",
      "⠗⠚⠉",
      /(?<=((^|[ ,.])(un)?))rejoice(?=((d|ful(ly)?|fullness)?([ ,.]|$)))/g,
    ],
    [
      "receive",
      "⠗⠉⠧",
      /(?<=((^|[ ,.])(un|p)?))receive(?=((d|r|ership)?([ ,.]|$)))/g,
    ],
    ["perhaps", "⠏⠻⠓", /perhaps/g],
    ["oneself", "⠐⠕⠋", /oneself/g],
    ["neither", "⠝⠑⠊", /(?<=(^|[ ,.]))neither(?=([ ,.]|$))/g],
    ["himself", "⠓⠍⠋", /(?<=(^|[ ,.]))himself(?=([ ,.]|$))/g],
    ["herself", "⠓⠻⠋", /herself/g],
    ["declare", "⠙⠉⠇", /(?<=((^|[ ,.])(un)?))declare(?=((d|r)?([ ,.]|$)))/g],
    [
      "deceive",
      "⠙⠉⠧",
      /(?<=((^|[ ,.])(un|arch)?))deceive(?=((d|r)?([ ,.]|$)))/g,
    ],
    [
      "braille",
      "⠃⠗⠇",
      /(?<=((^|[ ,.])(mis|re|un)?))braille(?=((d|r|writ(er|ing)|y)?([ ,.]|$)))/g,
    ],

    [
      "between",
      "⠆⠞",
      /(?<=((^|[ ,.])(in)?))between(?=((deck|time|while)?([ ,.]|$)))/g,
    ],
    ["beneath", "⠆⠝", /(?<=(^|[ ,.]))beneath(?=((deck|ground)?([ ,.]|$)))/g],
    ["because", "⠆⠉", /(?<=(^|[ ,.]))because(?=((of)?([ ,.]|$)))/g],
    ["already", "⠁⠇⠗", /(?<=(^|[ ,.]))already(?=([ ,.]|$))/g],
    ["against", "⠁⠛⠌", /against/g],
    [
      "friend",
      "⠋⠗",
      /(?<=((^|[ ,.])(be|boy|de|gal|girl|lady|school|un)?))friend(?=((less(ness)?|li(er|es|est|ness(es)?)|ly|ship(s)?|s|ed))?([ ,.]|$))/g,
    ],
    ["spirit", "⠸⠎", /spirit/g],
    ["should", "⠩⠙", /should/g],
    ["myself", "⠍⠽⠋", /(?<=(^|[ ,.]))myself(?=([ ,.]|$))/g],
    ["mother", "⠐⠍", /mother/g],
    [
      "little",
      "⠇⠇",
      /(?<=((^|[ ,.])(be)?))little(?=((d|ne(ss(es)?|ck)|r|st|ment)?([ ,.]|$)))/g,
    ], //
    [
      "letter",
      "⠇⠗",
      /(?<=((^|[ ,.])(blood|chain|hate|love|news)?))letter(?=((bomb(ed|er|ing)?|box(ed|er|es|ing)?|er|ed)?([ ,.]|$)))/g,
    ],
    ["itself", "⠭⠋", /(?<=(^|[ ,.]))itself(?=([ ,.]|$))/g],
    ["either", "⠑⠊", /(?<=(^|[ ,.]))either(?=((way(s?))?([ ,.]|$)))/g],
    ["father", "⠐⠋", /father/g],
    ["cannot", "⠸⠉", /cannot/g],
    ["beyond", "⠆⠽", /(?<=(^|[ ,.]))beyond(?=([ ,.]|$))/g],
    ["beside", "⠆⠎", /(?<=(^|[ ,.]))beside(?=((s)?([ ,.]|$)))/g],
    ["behind", "⠆⠓", /(?<=(^|[ ,.]))behind(?=([ ,.]|$))/g],
    ["before", "⠆⠋", /(?<=(^|[ ,.]))before(?=([ ,.]|$))/g],
    ["always", "⠁⠇⠺", /(?<=(^|[ ,.]))always(?=([ ,.]|$))/g],
    ["almost", "⠁⠇⠍", /(?<=(^|[ ,.]))almost(?=([ ,.]|$))/g],
    ["across", "⠁⠉⠗", /(?<=((^|[ ,.])(read)?))across(?=([ ,.]|$))/g],
    ["first", "⠋⠌", /first/g],
    ["whose", "⠘⠱", /whose/g],
    ["young", "⠐⠽", /young/g],
    [
      "would",
      "⠺⠙",
      /(?<=((^|[ ,.])('t)?))would(?=((|a|e?st|(n't)?('ve)?)?([ ,.]|$)))/g,
    ], //
    ["world", "⠸⠺", /world/g],
    ["where", "⠐⠱", /where/g],
    ["under", "⠐⠥", /under/g],
    ["today", "⠞⠙", /(?<=(^|[ ,.]))today(?=([ ,.]|$))/g],
    ["those", "⠘⠹", /those/g],
    ["these", "⠘⠮", /these/g],
    ["there", "⠐⠮", /there/g],
    ["their", "⠸⠮", /their/g],
    ["right", "⠐⠗", /right/g],
    [
      "quick",
      "⠟⠅",
      /(?<=((^|[ ,.])(un|super|double)?))quick(?=((draw|en(er|d|ing|)?|er|est|fir(e|ing)?|fr(eez(e|ing)|ozen?)|i(e|sh(ly)?)|lime|l?y|ness(es)?|silver(ed|ing)?|s(and|et|nap|tep(ped|per|ping))|tempered|time|witted(ly|ness)?)?([ ,.]|$)))/g,
    ],

    ["ought", "⠐⠳", /ought/g],
    [
      "great",
      "⠛⠗⠞",
      /(?<=(^|[ ,.]))great(?=((coat|en(ed|er|ing)?|er|est|hearted(ly|ness(es)?)?|ly|ness(es)?|sword)([ ,.]|$)))/g,
    ],
    [
      "could",
      "⠉⠙",
      /(?<=(^|[ ,.]))could(?=((|a|e?st|(n't)?('ve)?)?([ ,.]|$)))/g,
    ],
    [
      "blind",
      "⠃⠇",
      /(?<=((^|[ ,.])(colou?r|deaf|pur|snow|un)?))blind(?=((fish|fold(ed|er|ing)?|ly|ness(es)?|si(ded|der|ding|ght)|stor(y|ies)|worm)([ ,.]|$)))/g,
    ],
    ["below", "⠆⠇", /(?<=(^|[ ,.]))below(?=([ ,.]|$))/g],
    ["again", "⠁⠛", /(?<=((^|[ ,.])((h|th|wh)ere(in)?)?))again(?=([ ,.]|$))/g],
    [
      "after",
      "⠁⠋",
      /(?<=((^|[ ,.])((h|th|wh)ere(in)?|morning)?))after(?=((burn(ed|er|ing)?|care|clap|damp|dark|deck|dinner|flow|glow|guard|hatch(es)?|hour|li(fe|ves)|light|lunch(es)?|market|match(es)?|math|meeting|most|pain|part(y|ies)|piece|play|sale|school|sensation|shave|shock|show(er)?|supper|taste|tax(es)?|thought|time|treatment|word|work|world|battle|birth)?([ ,.]|$)))/g,
    ],
    [
      "above",
      "⠁⠃⠧",
      /(?<=(^|[ ,.]))above(?=((board|ground|mentioned)?([ ,.]|$)))/g,
    ],
    [
      "about",
      "⠁⠃",
      /(?<=((^|[ ,.])(((th|h)ere|(we|ea)st|gad|knock|lay|(nor|sou)th|right|rou(nd|st)|run|stir|turn|walk))?))about(?=(fac(e|ed|er|ing)|s|turn(ed)?)?([ ,.]|$))/g,
    ],
    ["ever", "⠐⠑", /ever/g],
    ["your", "⠽⠗", /(?<=(^|[ ,.]))your(?=((s)?([ ,.]|$)))/g],
    ["work", "⠐⠺", /work/g],
    ["word", "⠘⠺", /word/g],
    ["with", "⠾", /with/g],
    ["upon", "⠘⠥", /upon/g],
    ["time", "⠐⠞", /time/g],
    ["such", "⠎⠡", /(?<=(^|[ ,.]))such(?=((like|ness)?([ ,.]|$)))/g],
    ["some", "⠐⠎", /some/g],
    [
      "said",
      "⠎⠙",
      /(?<=((^|[ ,.])(a?fore|gain|mis)?))said(?=((e?st)?([ ,.]|$)))/g,
    ],
    ["part", "⠐⠏", /part/g],
    [
      "paid",
      "⠏⠙",
      /(?<=((^|[ ,.])(highest\-|highly|ill|lowly|over|poorly|post|p?re|under|un|well)?))paid(?=([ ,.]|$))/g,
    ],
    ["name", "⠐⠝", /name/g],
    ["must", "⠍⠌", /must/g],
    ["much", "⠍⠡", /much/g],
    ["many", "⠸⠍", /many/g],
    ["lord", "⠐⠇", /lord/g],
    ["know", "⠐⠅", /know/g],
    ["here", "⠐⠓", /here/g],
    [
      "good",
      "⠛⠙",
      /(?<=((^|[ ,.])(feel|super|scatter)?))good(?=((by|bye|byeing|day|er|est|evening|fellow|fellowship|hearted|heartedly|heartedness|humor|humored|humoredly|humoredness|humorednesses|ie|ish|li(er|est|ness)|look(er|ing)?|ly|nature|natured(ly|ness)|ness(es)?|night|sized|tempered|temperedly|time|willed|y)?([ ,.]|$)))/g,
    ],
    ["also", "⠁⠇", /(?<=(^|[ ,.]))also(?=([ ,.]|$))/g],

    ["ance", "⠨⠑", /(?<=[^ ]+)ance(?=([ ,.]|(\(|\))|$))/g],
    ["ment", "⠰⠞", /(?<=[^ ]+)ment(?=([ ,.]|(\(|\))|$))/g],
    ["ness", "⠰⠎", /(?<=[^ ]+)ness(?=([ ,.]|(\(|\))|$))/g],
    ["ound", "⠨⠙", /(?<=[^ ]+)ound(?=([ ,.]|(\(|\))|$))/g],
    ["ount", "⠨⠞", /(?<=[^ ]+)ount(?=([ ,.]|(\(|\))|$))/g],
    ["sion", "⠨⠝", /(?<=[^ ]+)sion(?=([ ,.]|(\(|\))|$))/g],
    ["tion", "⠰⠝", /(?<=[^ ]+)tion(?=([ ,.]|(\(|\))|$))/g],
    ["ence", "⠰⠑", /(?<=[^ ]+)ence(?=([ ,.]|(\(|\))|$))/g],
    ["less", "⠨⠎", /(?<=[^ ]+)less(?=([ ,.]|(\(|\))|$))/g],
    ["ff", "⠖", /(?<=[^⠐⠌ ]+)ff(?=[^ ]+)/g],
    ["ful", "⠰⠇", /(?<=[^ ]+)ful(?=([ ,.]|$))/g],
    ["gg", "⠶", /(?<=[^ ⠐⠄]+)gg(?=[^ ]+)/gi],
    ["ity", "⠰⠽", /(?<=[^ ]+)ity(?=([ ,.]|$))/g],
    ["ong", "⠰⠛", /(?<=[^ ]+)ong(?=([ ,.]|$))/g],
    ["bb", "⠆", /(?<=[^ ]+)bb(?=[^ ]+)/g],
    ["cc", "⠒", /(?<!(⠼[^ ]+)|⠼)(?<=[^ ]+)cc(?=[^ ]+)/g],
    ["con", "⠒", /(?<=([ ,.]|^))con(?=[^ ]+)/g],
    ["dis", "⠲", /(?<=([ ,.]|^))dis(?!⠐⠜)(?=[^ ⠲]+)/g],
    ["ea", "⠂", /(?<!(⠼[^ ]+)|⠼)(?<=([^ ]+))ea(?=[^ ]+)/g],
    ["be", "⠆", /(?<=([ ,.]|^))be(?=[^ ]+)/g],
    ["for", "⠿", /for/g],
    ["the", "⠮", /the/g],
    ["one", "⠐⠕", /one/g],
    ["ing", "⠬", /ing/g],
    ["him", "⠓⠍", /him/g],
    ["had", "⠸⠓", /had/g],
    ["day", "⠐⠙", /day/g],
    ["and", "⠯", /(?<!⠈)and/g],
    ["ch", "⠡", /(?<!⠸)ch/g],
    ["gh", "⠣", /(?<![⠐⠸⠈⠨])gh/g],
    ["er", "⠻", /er/g],
    ["en", "⠢", /(?<!⠈)en/g],
    ["wh", "⠱", /wh/g],
    ["th", "⠹", /(?<!⠸)th/g],
    ["st", "⠌", /(?<!⠸)st/g],
    ["sh", "⠩", /sh/g],
    ["ow", "⠪", /ow/g],
    ["ou", "⠳", /ou/g],
    ["of", "⠷", /of/g],
    ["ed", "⠫", /ed/g],
    ["in", "⠔", /(?<!⠐)in/g],
    ["ar", "⠜", /(?<![⠐⠸⠈⠨])ar/g],
  ],
  punctuation: [
    ["⠼", /\d+[.,]?\d*/g, /⠼(?=\d+)/g],
    ["⠠", /(?<=([^A-Z]|^))[A-Z](?=([^A-Z]|$))/g, /(?<!⠠)⠠(?![⠤⠠])/g],
    ["⠠⠠", /[A-Z]{2,}/g, /(⠠{2})/g],
    ["⠰", /(?<=\d)[a-j]+/g, /(?<=\d)⠰/g],
    //["⠦",/(?<!(⠦[^"]*))"(?=([^"]+"))/g,/(?<=[^⠠⠘⠄⠀])⠦(?=(.*[^⠠⠨⠘⠄⠀]⠴))/g,"⠠⠶",],
    //["⠴", /(?<=([^⠘⠄]⠦.*))"/g, /(?<=(".+))⠴/g, "⠠⠶"],
  ],
};

export default brailleTable;
