let brailleTable = {
  alphabete: [
    ["a", "⠁"],
    ["b", "⠃"],
    ["c", "⠉"],
    ["d", "⠙"],
    ["e", "⠑"],
    ["f", "⠋"],
    ["g", "⠛"],
    ["h", "⠓"],
    ["i", "⠊"],
    ["j", "⠚"],
    ["k", "⠅"],
    ["l", "⠇"],
    ["m", "⠍"],
    ["n", "⠝"],
    ["o", "⠕"],
    ["p", "⠏"],
    ["q", "⠟"],
    ["r", "⠗"],
    ["s", "⠎"],
    ["t", "⠞"],
    ["u", "⠥"],
    ["v", "⠧"],
    ["w", "⠺"],
    ["x", "⠭"],
    ["y", "⠽"],
    ["z", "⠵"],
    [",", "⠂"],
    [";", "⠆"],
    [":", "⠒"],
    [".", "⠲"],
    ["?", "⠦"],
    ["!", "⠖"],
    ["‘", "⠄"],
    ["“", "⠄⠶"],
    ["“", "⠘⠦"],
    ["”", "⠘⠴"],
    ["‘", "⠄⠦"],
    ["’", "⠄⠴"],
    ['"', "⠠⠶"],
    ["'", "⠄"],
    ["(", "⠐⠣"],
    [")", "⠐⠜"],
    ["{", "⠸⠣"],
    ["}", "⠸⠜"],
    ["&", "⠈⠯"],
    ["<", "⠈⠣"],
    [">", "⠈⠜"],
    ["[", "⠨⠣"],
    ["]", "⠨⠜"],
    ["%", "⠨⠴"],
    ["#", "⠸⠹"],
    ["^", "⠈⠢"],
    ["@", "⠈⠁"],
    ["/", "⠸⠌"],
    ["\\", "⠸⠡"],
    ["$", "⠈⠎"],
    ["£", "⠈⠇"],
    ["€", "⠈⠑"],
    ["¥", "⠈⠽"],
    [" ", "⠀"], //space
    ["-", "⠤"], //hyphen
    ["–", "⠠⠤"], //en dash
    ["—", "⠐⠠⠤"], //em dash
  ],
  numbers: [
    ["1", "⠁"],
    ["2", "⠃"],
    ["3", "⠉"],
    ["4", "⠙"],
    ["5", "⠑"],
    ["6", "⠋"],
    ["7", "⠛"],
    ["8", "⠓"],
    ["9", "⠊"],
    ["0", "⠚"],
    ["=", "⠐⠶"],
    ["+", "⠐⠖"],
    ["*", "⠐⠔"],
  ],
  grade2: [
    ["knowledge", "⠅", /(?<=([ ⠠]|^))knowledge(?=([ ,\.]|$))/g],
    ["enough", "⠢", /(?<=([ ⠠]|^))enough(?=([ ,\.]|$))/g],
    ["people", "⠏", /(?<=([ ⠠]|^))people(?=([ ,\.]|$))/g],
    ["rather", "⠗", /(?<=([ ⠠]|^))rather(?=([ ,\.]|$))/g],
    ["child", "⠡", /(?<=([ ⠠]|^))child(?=([ ,\.]|$))/g],
    ["every", "⠑", /(?<=([ ⠠]|^))every(?=([ ,\.]|$))/g],
    ["quite", "⠟", /(?<=([ ⠠]|^))quite(?=([ ,\.]|$))/g],
    ["shall", "⠩", /(?<=([ ⠠]|^))shall(?=([ ,\.]|$))/g],
    ["still", "⠌", /(?<=([ ⠠]|^))still(?=([ ,\.]|$))/g],
    ["which", "⠱", /(?<=([ ⠠]|^))which(?=([ ,\.]|$))/g],
    ["from", "⠋", /(?<=([ ⠠]|^))from(?=([ ,\.]|$))/g],
    ["have", "⠓", /(?<=([ ⠠]|^))have(?=([ ,\.]|$))/g],
    ["just", "⠚", /(?<=([ ⠠]|^))just(?=([ ,\.]|$))/g],
    ["like", "⠇", /(?<=([ ⠠]|^))like(?=([ ,\.]|$))/g],
    ["more", "⠍", /(?<=([ ⠠]|^))more(?=([ ,\.]|$))/g],
    ["that", "⠞", /(?<=([ ⠠]|^))that(?=([ ,\.]|$))/g],
    ["this", "⠹", /(?<=([ ⠠]|^))this(?=([ ,\.]|$))/g],
    ["very", "⠧", /(?<=([ ⠠]|^))very(?=([ ,\.]|$))/g],
    ["were", "⠶", /(?<=([ ⠠]|^))were(?=([ ,\.]|$))/g],
    ["will", "⠺", /(?<=([ ⠠]|^))will(?=([ ,\.]|$))/g],
    ["but", "⠃", /(?<=([ ⠠]|^))but(?=([ ,\.]|$))/g],
    ["can", "⠉", /(?<=([ ⠠]|^))can(?=([ ,\.]|$))/g],
    ["his", "⠦", /(?<=([ ⠠]|^))his(?=([ ,\.]|$))/g],
    ["its", "⠭⠎", /(?<=([ ⠠]|^))its(?=([ ,\.]|$))/g],
    ["not", "⠝", /(?<=([ ⠠]|^))not(?=([ ,\.]|$))/g],
    ["out", "⠳", /(?<=([ ⠠]|^))out(?=([ ,\.]|$))/g],
    ["was", "⠴", /(?<=([ ⠠]|^))was(?=([ ,\.]|$))/g],
    ["you", "⠽", /(?<=([ ⠠]|^))you(?=([ ,\.]|$))/g],
    ["as", "⠵", /(?<=([ ⠠]|^))as(?=([ ,\.]|$))/g],
    ["be", "⠆", /(?<=([ ⠠]|^))be(?=([ ,\.]|$))/g],
    ["do", "⠙", /(?<=([ ⠠]|^))do(?=([ ,\.]|$))/g],
    ["go", "⠛", /(?<=([ ⠠]|^))go(?=([ ,\.]|$))/g],
    ["it", "⠭", /(?<=([ ⠠]|^))it(?=([ ,\.]|$))/g],
    ["so", "⠎", /(?<=([ ⠠]|^))so(?=([ ,\.]|$))/g],
    ["us", "⠥", /(?<=([ ⠠]|^))us(?=([ ,\.]|$))/g],

    ["yourselves", "⠽⠗⠧⠎", /yourselves/g],
    ["themselves", "⠮⠍⠧⠎", /themselves/g],
    ["perceiving", "⠏⠻⠉⠧⠛", /perceiving/g],
    ["conceiving", "⠒⠉⠧⠛", /conceiving/g],
    ["altogether", "⠁⠇⠞", /altogether/g],
    ["rejoicing", "⠗⠚⠉⠛", /rejoicing/g],
    ["receiving", "⠗⠉⠧⠛", /receiving/g],
    ["ourselves", "⠳⠗⠧⠎", /ourselves/g],
    ["necessary", "⠝⠑⠉", /necessary/g],
    ["immediate", "⠊⠍⠍", /immediate/g],
    ["declaring", "⠙⠉⠇⠛", /declaring/g],
    ["deceiving", "⠙⠉⠧⠛", /deceiving/g],
    ["character", "⠐⠡", /character/g],
    ["afterward", "⠁⠋⠺", /afterward/g],
    ["afternoon", "⠁⠋⠝", /afternoon/g],
    ["according", "⠁⠉", /according/g],
    ["yourself", "⠽⠗⠋", /yourself/g],
    ["tomorrow", "⠞⠍", /tomorrow/g],
    ["together", "⠞⠛⠗", /together/g],
    ["question", "⠐⠟", /question/g],
    ["perceive", "⠏⠻⠉⠧", /perceive/g],
    ["conceive", "⠒⠉⠧", /conceive/g],
    ["children", "⠡⠝", /children/g],
    ["although", "⠁⠇⠹", /although/g],
    ["tonight", "⠞⠝", /tonight/g],
    ["thyself", "⠹⠽⠋", /thyself/g],
    ["through", "⠐⠹", /through/g],
    ["rejoice", "⠗⠚⠉", /rejoice/g],
    ["receive", "⠗⠉⠧", /receive/g],
    ["perhaps", "⠏⠻⠓", /perhaps/g],
    ["oneself", "⠐⠕⠋", /oneself/g],
    ["neither", "⠝⠑⠊", /neither/g],
    ["himself", "⠓⠍⠋", /himself/g],
    ["herself", "⠓⠻⠋", /herself/g],
    ["declare", "⠙⠉⠇", /declare/g],
    ["deceive", "⠙⠉⠧", /deceive/g],
    ["braille", "⠃⠗⠇", /braille/g],
    ["between", "⠆⠞", /between/g],
    ["beneath", "⠆⠝", /beneath/g],
    ["because", "⠆⠉", /because/g],
    ["already", "⠁⠇⠗", /already/g],
    ["against", "⠁⠛⠌", /against/g],
    ["friend", "⠋⠗", /friend/g],
    ["spirit", "⠸⠎", /spirit/g],
    ["should", "⠩⠙", /should/g],
    ["myself", "⠍⠽⠋", /myself/g],
    ["mother", "⠐⠍", /mother/g],
    ["little", "⠇⠇", /little/g],
    ["letter", "⠇⠗", /letter/g],
    ["itself", "⠭⠋", /itself/g],
    ["either", "⠑⠊", /either/g],
    ["father", "⠐⠋", /father/g],
    ["cannot", "⠸⠉", /cannot/g],
    ["beyond", "⠆⠽", /beyond/g],
    ["beside", "⠆⠎", /beside/g],
    ["behind", "⠆⠓", /behind/g],
    ["before", "⠆⠋", /before/g],
    ["always", "⠁⠇⠺", /always/g],
    ["almost", "⠁⠇⠍", /almost/g],
    ["across", "⠁⠉⠗", /across/g],
    ["first", "⠋⠌", /first/g],
    ["whose", "⠘⠱", /whose/g],
    ["young", "⠐⠽", /young/g],
    ["would", "⠺⠙", /would/g],
    ["world", "⠸⠺", /world/g],
    ["where", "⠐⠱", /where/g],
    ["under", "⠐⠥", /under/g],
    ["today", "⠞⠙", /today/g],
    ["those", "⠘⠹", /those/g],
    ["these", "⠘⠮", /these/g],
    ["there", "⠐⠮", /there/g],
    ["their", "⠸⠮", /their/g],
    ["right", "⠐⠗", /right/g],
    ["quick", "⠟⠅", /quick/g],
    ["ought", "⠐⠳", /ought/g],
    ["great", "⠛⠗⠞", /great/g],
    ["could", "⠉⠙", /could/g],
    ["blind", "⠃⠇", /blind/g],
    ["below", "⠆⠇", /below/g],
    ["again", "⠁⠛", /again/g],
    ["after", "⠁⠋", /after/g],
    ["above", "⠁⠃⠧", /above/g],
    ["about", "⠁⠃", /about/g],
    ["ever", "⠐⠑", /ever/g],
    ["your", "⠽⠗", /your/g],
    ["work", "⠐⠺", /work/g],
    ["word", "⠘⠺", /word/g],
    ["with", "⠾", /with/g],
    ["upon", "⠘⠥", /upon/g],
    ["time", "⠐⠞", /time/g],
    ["such", "⠎⠡", /such/g],
    ["some", "⠐⠎", /some/g],
    ["said", "⠎⠙", /said/g],
    ["part", "⠐⠏", /part/g],
    ["paid", "⠏⠙", /paid/g],
    ["name", "⠐⠝", /name/g],
    ["must", "⠍⠌", /must/g],
    ["much", "⠍⠡", /much/g],
    ["many", "⠸⠍", /many/g],
    ["lord", "⠐⠇", /lord/g],
    ["know", "⠐⠅", /know/g],
    ["here", "⠐⠓", /here/g],
    ["good", "⠛⠙", /good/g],
    ["also", "⠁⠇", /also/g],

    ["ance", "⠨⠑", /(?<=[^ ]+)ance(?=([ ,\.]|$))/g],
    ["ment", "⠰⠞", /(?<=[^ ]+)ment(?=([ ,\.]|$))/g],
    ["ness", "⠰⠎", /(?<=[^ ]+)ness(?=([ ,\.]|$))/g],
    ["ound", "⠨⠙", /(?<=[^ ]+)ound(?=([ ,\.]|$))/g],
    ["ount", "⠨⠞", /(?<=[^ ]+)ount(?=([ ,\.]|$))/g],
    ["sion", "⠨⠝", /(?<=[^ ]+)sion(?=([ ,\.]|$))/g],
    ["tion", "⠰⠝", /(?<=[^ ]+)tion(?=([ ,\.]|$))/g],
    ["ence", "⠰⠑", /(?<=[^ ]+)ence(?=([ ,\.]|$))/g],
    ["less", "⠨⠎", /(?<=[^ ]+)less(?=([ ,\.]|$))/g],
    ["ff", "⠖", /(?<=[^ ]+)ff(?=[^ ]+)/g],
    ["ful", "⠰⠇", /(?<=[^ ]+)ful(?=([ ,\.]|$))/g],
    ["gg", "⠶", /(?<=[^ ]+)gg(?=[^ ]+)/g],
    ["ity", "⠰⠽", /(?<=[^ ]+)ity(?=([ ,\.]|$))/g],
    ["ong", "⠰⠛", /(?<=[^ ]+)ong(?=([ ,\.]|$))/g],
    ["bb", "⠆", /(?<=[^ ]+)bb(?=[^ ]+)/g],
    ["cc", "⠒", /(?<=[^ ]+)cc(?=[^ ]+)/g],
    ["con", "⠒", /(?<=( |^))con(?=[^ ]+)/g],
    ["dis", "⠲", /(?<=( |^))dis(?=[^ ]+)/g],
    ["ea", "⠂", /(?<=[^ ]+)ea(?=[^ ]+)/g],
    ["be", "⠆", /(?<=( |^))be(?=[^ ]+)/g],
    ["for", "⠿", /for/g],
    ["the", "⠮", /the/g],
    ["one", "⠐⠕", /one/g],
    ["ing", "⠬", /ing/g],
    ["him", "⠓⠍", /him/g],
    ["had", "⠸⠓", /had/g],
    ["day", "⠐⠙", /day/g],
    ["and", "⠯", /and/g],
    ["ch", "⠡", /ch/g],
    ["gh", "⠣", /gh/g],
    ["er", "⠻", /er/g],
    ["en", "⠢", /en/g],
    ["wh", "⠱", /wh/g],
    ["th", "⠹", /th/g],
    ["st", "⠌", /st/g],
    ["sh", "⠩", /sh/g],
    ["ow", "⠪", /ow/g],
    ["ou", "⠳", /ou/g],
    ["of", "⠷", /of/g],
    ["ed", "⠫", /ed/g],
    ["in", "⠔", /in/g],
    ["ar", "⠜", /ar/g],
  ],
  punctuation: [
    ["numeric indicator", "⠼", /\d+[.,]?\d*/g, /⠼(?=\d+)/g],
    [
      "capital letter",
      "⠠",
      /(?<=([^A-Z]|^))[A-Z](?=([^A-Z]|$))/g,
      /(?<!⠠)⠠(?![⠤⠠])/g,
    ],
    ["capital word", "⠠⠠", /[A-Z]{2,}/g, /(⠠{2})/g],
    ["word letter followed by number", "⠰", /(?<=\d)[a-j]+/g, /(?<=\d)⠰/g],
  ],
};

export default brailleTable;

/*(function addregex() {
  const arr = [];
  grade2.forEach((cell) => {
    let re;
    if (/[\s]/g.test(cell[0]) === false) {
      if (/^[a-zA-Z]+$/g.test(cell[0])) {
        re = new RegExp(` ${cell[0].replaceAll("", "")} `, "g");
      } else if (/^[a-zA-Z]+$/g.test(cell[0])) {
        re = new RegExp(`${cell[0]}`, "g");
      } else if (/^([a-zA-Z]+)\^$/g.test(cell[0])) {
        re = new RegExp(`${cell[0].replaceAll("^", "")}[^ ]`, "g");
      } else if (/^\^([a-zA-Z]+)$/g.test(cell[0])) {
        re = new RegExp(`[^ ]${cell[0].replaceAll("^", "")}`, "g");
      } else if (/^\^([a-zA-Z]+)$\^/g.test(cell[0])) {
        re = new RegExp(`[^ ]${cell[0].replaceAll("^", "")}[^ ]`, "g");
      }
    } else {
      if (cell[0] === "numeric indicator") {
        re = new RegExp(`\d+[\.,\/]?\d*`, "g");
      } else if (cell[0] === "capital word") {
        re = new RegExp(`[A-Z]{2,}`, "g");
      } else if (cell[0] === "capital letter") {
        re = new RegExp(`[A-Z][A-Z][A-Z]`, "g");
      }
    }
    arr.push([cell[0], cell[1], `${re}`]);
  });
  console.log(arr);
})()*/
